# Generated by Codex on 2026-06-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("username", models.CharField(db_index=True, max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("UserSelected", "User Selected"),
                            ("FileUpload", "File Upload"),
                            ("LLMCall", "LLM Call"),
                            ("LLMSuccess", "LLM Success"),
                            ("LLMFailure", "LLM Failure"),
                            ("AuditFailure", "Audit Failure"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("action", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("route", models.CharField(blank=True, default="", max_length=255)),
                ("method", models.CharField(blank=True, default="", max_length=12)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("task_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("accession_no", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("artifact_path", models.CharField(blank=True, default="", max_length=500)),
                ("artifact_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("artifact_size", models.BigIntegerField(blank=True, null=True)),
                ("event_hash", models.CharField(blank=True, default="", max_length=64)),
                ("previous_hash", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["category", "timestamp"], name="audit_audit_category_6af545_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["username", "timestamp"], name="audit_audit_username_35bf26_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["task_id", "timestamp"], name="audit_audit_task_id_f15d27_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["accession_no", "timestamp"], name="audit_audit_access_6abe0a_idx"),
        ),
    ]
