# Generated by Django 5.2.15 on 2026-06-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="audit_audit_categor_329c61_idx",
            old_name="audit_audit_category_6af545_idx",
        ),
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="audit_audit_usernam_4975f9_idx",
            old_name="audit_audit_username_35bf26_idx",
        ),
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="audit_audit_task_id_b50c3e_idx",
            old_name="audit_audit_task_id_f15d27_idx",
        ),
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="audit_audit_accessi_95db26_idx",
            old_name="audit_audit_access_6abe0a_idx",
        ),
    ]
