# Generated by Django 5.2.15 on 2026-06-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cxrstudy",
            new_name="upload_cxrs_workpla_3fc2cb_idx",
            old_name="upload_cxrs_workpla_61ddfd_idx",
        ),
        migrations.RenameIndex(
            model_name="cxrstudy",
            new_name="upload_cxrs_procedu_4d60bc_idx",
            old_name="upload_cxrs_procedu_d8e6d2_idx",
        ),
        migrations.RenameIndex(
            model_name="cxrstudy",
            new_name="upload_cxrs_gt_llm_601455_idx",
            old_name="upload_cxrs_gt_llm_7f42c0_idx",
        ),
        migrations.RenameIndex(
            model_name="cxrstudy",
            new_name="upload_cxrs_lunit_b_8f8bd1_idx",
            old_name="upload_cxrs_lunit_b_e6c7db_idx",
        ),
        migrations.RenameIndex(
            model_name="cxrstudy",
            new_name="upload_cxrs_process_a466c7_idx",
            old_name="upload_cxrs_process_d1d88f_idx",
        ),
        migrations.AlterField(
            model_name="processingtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="queued",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
